# Generated by Django 2.2.7 on 2020-01-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APELLIDOS', models.CharField(max_length=50)),
                ('NOMBRES', models.CharField(max_length=50)),
                ('CI', models.IntegerField()),
                ('CORREO_UCAB', models.CharField(max_length=30)),
                ('CORREO_P', models.CharField(max_length=30)),
                ('TELEFONO1', models.CharField(max_length=15)),
                ('TELEFONO2', models.CharField(max_length=15)),
                ('OBSERVACIONES', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('CODIGO', models.IntegerField(primary_key=True, serialize=False)),
                ('TITULO', models.CharField(max_length=150)),
                ('FECHA_ENTREGA', models.DateTimeField(verbose_name='FECHA ENTREGA')),
                ('ALUMNO1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno1', to='TesisApp.Persona')),
                ('ALUMNO2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno2', to='TesisApp.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Status_Propuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS_PROPUESTA', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Status_TG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS_TG', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TERM', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPO_PERSONA', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TG',
            fields=[
                ('CODIGO', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('TITULO', models.CharField(max_length=100)),
                ('NRC', models.CharField(max_length=10)),
                ('DESCRIPCION', models.CharField(max_length=50)),
                ('CAT_TEMATICA', models.CharField(max_length=50)),
                ('FECHA_ENTREGA', models.DateTimeField(verbose_name='FECHA ENTREGA')),
                ('NOMBRE_EMPRESA', models.CharField(max_length=50)),
                ('PROPUESTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuesta', to='TesisApp.Propuesta')),
                ('STATUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termTG', to='TesisApp.Status_TG')),
                ('TERM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termTG', to='TesisApp.Term')),
            ],
        ),
        migrations.AddField(
            model_name='propuesta',
            name='STATUS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusPropuesta', to='TesisApp.Status_Propuesta'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='TERM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termPropuesta', to='TesisApp.Term'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='TUTOR_A',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorA', to='TesisApp.Persona'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='TUTOR_E',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorE', to='TesisApp.Persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='TIPO_PERSONA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoPersona', to='TesisApp.Tipo_Persona'),
        ),
        migrations.CreateModel(
            name='Defensa',
            fields=[
                ('CODIGO', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('FECHA_DEFENSA', models.DateTimeField(verbose_name='FECHA DEFENSA')),
                ('ASIST_J1', models.IntegerField()),
                ('ASIST_J2', models.IntegerField()),
                ('ASIST_JS', models.IntegerField()),
                ('CALIFICACION', models.IntegerField()),
                ('M_PUBLIC', models.IntegerField()),
                ('M_HONOR', models.IntegerField()),
                ('CORRECCIONES', models.IntegerField()),
                ('FECHA_CORREC', models.DateTimeField(verbose_name='FECHA CORRECCIONES')),
                ('NOTA_CARGADA', models.IntegerField()),
                ('OBSERVACIONES', models.CharField(max_length=200)),
                ('JURADO1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurado1', to='TesisApp.Persona')),
                ('JURADO2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurado2', to='TesisApp.Persona')),
                ('JURADO_S', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juradoS', to='TesisApp.Persona')),
                ('TG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TG', to='TesisApp.TG')),
            ],
        ),
    ]
