# Generated by Django 2.2.7 on 2020-01-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TesisApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_propuesta',
            name='STATUS_PROPUESTA',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='status_tg',
            name='STATUS_TG',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='term',
            name='TERM',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tipo_persona',
            name='TIPO_PERSONA',
            field=models.CharField(max_length=15),
        ),
    ]
