# Generated by Django 2.2.7 on 2020-01-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TesisApp', '0002_auto_20200108_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_tg',
            name='STATUS_TG',
            field=models.CharField(max_length=40),
        ),
    ]
