# Generated by Django 2.2.7 on 2020-01-09 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TesisApp', '0003_auto_20200108_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='CORREO_UCAB',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='OBSERVACIONES',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='TELEFONO2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='ALUMNO2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumno2', to='TesisApp.Persona'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='TUTOR_E',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorE', to='TesisApp.Persona'),
        ),
    ]
