# Generated by Django 2.2.7 on 2020-01-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TesisApp', '0004_auto_20200109_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='ALUMNO2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumno2', to='TesisApp.Persona'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='TUTOR_E',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorE', to='TesisApp.Persona'),
        ),
    ]
